name: pactify
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.11.0
  firebase_auth: ^5.4.2
  cloud_firestore: ^5.6.3
  provider: ^6.1.2
  go_router: ^14.8.0
  rxdart: ^0.27.7
  google_sign_in: ^6.2.2
  flutter_svg: ^2.0.10+1
  image_picker: ^1.0.7
  image_picker_for_web: ^3.0.2
  http: ^1.2.0
  path: ^1.8.3
  cached_network_image: ^3.3.0
  flutter_image_compress: ^2.0.4
  path_provider: ^2.1.1
  # flutter_blurhash: ^0.7.0  # Supprimé car incompatible

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/Google__G__logo.svg
    - lib/assets/logo.jpg  # Ajout du logo

